urls:
  hotcopper: https://hotcopper.com.au/announcements/asx/
  marketindex: https://www.marketindex.com.au/asx-listed-companies
  afr_homepage: https://www.afr.com/
  afr_street_talk: https://www.afr.com/street-talk
  aus_homepage: https://www.theaustralian.com.au/
  aus_dataroom: https://www.theaustralian.com.au/business/dataroom
  aus_tradingday: https://www.theaustralian.com.au/business/trading-day

db:
  user: hrfswjuuruvuop
  password: 388836f9415afc6d66307027abac03b06129a7fc58e4fe6bf5da1ef62400dcba
  host: ec2-54-165-184-219.compute-1.amazonaws.com
  port: 5432
  name: dc9coa5oigpjt1
