urls:
  hotcopper: https://hotcopper.com.au/announcements/asx/
  marketindex: https://www.marketindex.com.au/asx-listed-companies

db:
  user: root
  password: Allblackscup_01
  host: mw-rds-db.cuas9c494acx.us-east-1.rds.amazonaws.com
  port: 5432
  name: stock_announcement_db